In [4]:
import pandas as pd

In [95]:
data = pd.read_csv('../Hong/crime_merged_data_v2.csv')

/Users/ksenia/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (242,252) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [96]:
data.head()

,Unnamed: 0,File,Judge,DistrictAttorney,ADA,Gap_days,Crimes,Judges,Defense,Y,...,AppealD_2012,AppealD_2013,AppealD_2014,AppealD_2015,AppealD_2016,AppealD_2017,FirstD_month_x,FirstD_month_y,AppealD_month_x,AppealD_month_y
0,0,2009_08295.htm.txt,"Peter L. Broderick, Sr., J.",Michael J. Violante,Thomas H. Brandt,735.0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0.866025,-0.500000,0.866025,-0.5
1,1,2009_08296.htm.txt,"Michael L. Dwyer, J.",Scott D. McNamara,Steven G. Cox,1103.0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0.866025,-0.500000,0.866025,-0.5
2,2,2009_08297.htm.txt,"Joseph E. Fahey, J.",William J. Fitzpatrick,Victoria M. White,1122.0,NaN,NaN,Legal Aid Society,1,...,0,0,0,0,0,0,0.500000,-0.866025,0.866025,-0.5
3,3,2009_08298.htm.txt,"Angelo J. Morinello, A.J.",NaN,NaN,742.0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0.866025,-0.500000,0.866025,-0.5
4,4,2009_08311.htm.txt,"Joseph E. Fahey, J.",William J. Fitzpatrick,James P. Maxwell,1667.0,NaN,NaN,Legal Aid Society,1,...,0,0,0,0,0,0,-0.500000,0.866025,0.866025,-0.5

In [97]:
data.columns.values

array(['Unnamed: 0', 'File', 'Judge', 'DistrictAttorney', 'ADA',
       'Gap_days', 'Crimes', 'Judges', 'Defense', 'Y', 'Crime_count',
       'Type_crime', 'Degree_crime', 'Type_crime_group',
       'Type_crime_group_kp', 'DUI', 'aggravated criminal contempt',
       'aggravated unlicensed operation of a motor vehicle',
       'aggravated vehicular homicide, manslaughter', 'arson', 'assault',
       'attempted arson', 'attempted assault', 'attempted burglary',
       'attempted conspiracy',
       'attempted course of sexual conduct against a child',
       'attempted criminal contempt',
       'attempted criminal possession of a controlled substance',
       'attempted criminal possession of a forged instrument',
       'attempted criminal possession of a weapon',
       'attempted criminal sale of a controlled substance',
       'attempted criminal sexual act',
       'attempted disseminating indecent material to minors',
       'attempted forgery', 'attempted grand larceny',
       'attempted kidnapping', 'attempted murder',
       'attempted promoting prison contraband', 'attempted rape',
       'attempted reckless endangerment', 'attempted robbery',
       'attempted sexual abuse', 'attempted sodomy',
       'attempted strangulation', 'bail jumping', 'burglary', 'conspiracy',
       'course of sexual conduct against a child', 'criminal contempt',
       'criminal facilitation', 'criminal mischief',
       'criminal possession of a controlled substance',
       'criminal possession of a forged instrument',
       'criminal possession of a weapon',
       'criminal possession of marihuana',
       'criminal possession of marijuana',
       'criminal possession of stolen property',
       'criminal possession of weapon',
       'criminal sale of a controlled substance',
       'criminal sale of a firearm', 'criminal sexual act',
       'criminal trespass', 'criminally negligent homicide',
       'driving while ability impaired by drugs',
       'endangering the welfare of a child', 'escape',
       'failure to register as a sex offender',
       'falsely reporting an incident', 'falsifying business records',
       'forgery', 'four counts of robbery', 'gang assault',
       'grand larceny', 'identity theft', 'insurance fraud', 'kidnapping',
       'manslaughter', 'menacing', 'murder',
       'obstructing governmental administration',
       'offering a false instrument for filing', 'petit larceny',
       'possessing a sexual performance by a child',
       'promoting prison contraband', 'promoting prostitution', 'rape',
       'reckless assault of a child', 'reckless endangerment',
       'resisting arrest', 'robbery', 'scheme to defraud', 'sex offender',
       'sexual abuse', 'sodomy', 'three counts of robbery',
       'two counts of burglary',
       'two counts of criminal possession of a weapon',
       'two counts of murder', 'two counts of robbery',
       'unauthorized use of a vehicle', 'unlawful imprisonment',
       'unlawful manufacture of methamphetamine', 'unlawful surveillance',
       'use of a child', 'vehicular manslaughter', 'welfare fraud',
       'fifth', 'first', 'fourth', 'second', 'seventh', 'sixth', 'third',
       'unanimous', 'appellant', 'da_last_name', 'da_female', 'da_black',
       'da_county', 'da_2003', 'da_2004', 'da_2005', 'da_2006', 'da_2007',
       'da_2008', 'da_2009', 'da_2010', 'da_2011', 'da_2012', 'da_2013',
       'da_2014', 'da_2015', 'da_2016', 'da_2017', 'da_2004-contested',
       'da_2005-contested', 'da_2007-contested', 'da_2008-contested',
       'da_2009-contested', 'da_2010-contested', 'da_2011-contested',
       'da_2012-contested', 'da_2013-contested', 'da_2014-contested',
       'da_2015-contested', 'da_university', 'jury verdict',
       'nonjury trial', 'plea of guilty', 'sever', 'suppress',
       'sufficient', 'instructions', 'coerce', 'ineffective counsel',
       'double jeopardy', 'speedy', 'coercion', 'youth', 'incapac',
       'resentenc', 'juror', 'mental', 'Court_County_Court',
       'Court_Court_Of_Claims', 'Court_Department_Of_Motor_Vehicles',
       'Court_Family_Court', 'Court_Missing', 'Court_Supreme_Court',
       'County_Albany County', 'County_Allegany County',
       'County_Bronx County', 'County_Broome County',
       'County_Cattaraugus County', 'County_Cayuga County',
       'County_Chautauqua County', 'County_Chemung County',
       'County_Chenango County', 'County_Clinton County',
       'County_Columbia County', 'County_Cortland County',
       'County_Delaware County', 'County_Dutchess County',
       'County_Erie County', 'County_Essex County',
       'County_Franklin County', 'County_Fulton County',
       'County_Genesee County', 'County_Greene County',
       'County_Hamilton County', 'County_Herkimer County',
       'County_Jefferson County', 'County_King County',
       'County_Kings County', 'County_Lawrence County',
       'County_Lewis County', 'County_Livingston County',
       'County_Madison County', 'County_Maricopa County',
       'County_Middlesex County', 'County_Missing', 'County_Monroe County',
       'County_Montgomery County', 'County_NY County',
       'County_Nassau County', 'County_Niagara County',
       'County_Oneida County', 'County_Onondaga County',
       'County_Ontario County', 'County_Orange County',
       'County_Orleans County', 'County_Ostego County',
       'County_Oswego County', 'County_Otsego County',
       'County_Putnam County', 'County_Queens County',
       'County_Rensselaer County', 'County_Richmond County',
       'County_Rockland County', 'County_Sarasota County',
       'County_Saratoga County', 'County_Schenectady County',
       'County_Schoharie County', 'County_Schuyler County',
       'County_Seneca County', 'County_Steuben County',
       'County_Suffolk County', 'County_Sullivan County',
       'County_Tioga County', 'County_Tompkins County',
       'County_Ulster County', 'County_Victoria County',
       'County_Warren County', 'County_Washington County',
       'County_Wayne County', 'County_Westchester County',
       'County_Wyoming County', 'County_Yates County',
       'County_York County', 'First_Name', 'Last_Name', 'law school',
       'grad year', 'elect', 'military', 'APD', 'Prof', 'female', 'CC',
       'SC-AJ', 'SC', 'SC-AJ & SC', 'start year', 'nycourts',
       'ballotpedia', '1976', '1980', '1981', '1984', '1985', '1986',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', 'retired', 'arrested',
       'lost-reelection', 'died', 'left', 'appointed-to-other-depart',
       'contested', 'f_Monday', 'f_Tuesday', 'f_Wednesday', 'f_Thursday',
       'f_Friday', 'f_Saturday', 'f_Sunday', 'a_Monday', 'a_Tuesday',
       'a_Wednesday', 'a_Thursday', 'a_Friday', 'a_Saturday', 'a_Sunday',
       'FirstD_1975.0', 'FirstD_1976.0', 'FirstD_1977.0', 'FirstD_1979.0',
       'FirstD_1980.0', 'FirstD_1981.0', 'FirstD_1982.0', 'FirstD_1983.0',
       'FirstD_1984.0', 'FirstD_1985.0', 'FirstD_1986.0', 'FirstD_1987.0',
       'FirstD_1988.0', 'FirstD_1989.0', 'FirstD_1990.0', 'FirstD_1991.0',
       'FirstD_1992.0', 'FirstD_1993.0', 'FirstD_1994.0', 'FirstD_1995.0',
       'FirstD_1996.0', 'FirstD_1997.0', 'FirstD_1998.0', 'FirstD_1999.0',
       'FirstD_2000.0', 'FirstD_2001.0', 'FirstD_2002.0', 'FirstD_2003.0',
       'FirstD_2004.0', 'FirstD_2005.0', 'FirstD_2006.0', 'FirstD_2007.0',
       'FirstD_2008.0', 'FirstD_2009.0', 'FirstD_2010.0', 'FirstD_2011.0',
       'FirstD_2012.0', 'FirstD_2013.0', 'FirstD_2014.0', 'FirstD_2015.0',
       'FirstD_2016.0', 'FirstD_2017.0', 'FirstD_2103.0', 'AppealD_2003',
       'AppealD_2004', 'AppealD_2005', 'AppealD_2006', 'AppealD_2007',
       'AppealD_2008', 'AppealD_2009', 'AppealD_2010', 'AppealD_2011',
       'AppealD_2012', 'AppealD_2013', 'AppealD_2014', 'AppealD_2015',
       'AppealD_2016', 'AppealD_2017', 'FirstD_month_x', 'FirstD_month_y',
       'AppealD_month_x', 'AppealD_month_y'], dtype=object)

In [9]:
data.describe()

,Unnamed: 0,CaseName,Gap_days,FirstD_weekday,AppealD_weekday,FirstD_month,AppealD_month,Y,FirstD_year,AppealD_year,...,f_Friday,f_Saturday,f_Sunday,a_Monday,a_Tuesday,a_Wednesday,a_Thursday,a_Friday,a_Saturday,a_Sunday
count,35232.000000,0.0,33707.000000,35232.000000,35232.0,33753.000000,35232.000000,35232.000000,33753.000000,35232.000000,...,35232.000000,35232.000000,35232.000000,35232.000000,35232.000000,35232.000000,35232.000000,35232.000000,35232.0,35232.0
mean,17615.500000,NaN,981.838550,0.997531,1.0,6.308299,6.483084,0.256897,2007.227032,2009.909628,...,0.153468,0.001391,0.001079,0.055802,0.297627,0.143733,0.289339,0.213499,0.0,0.0
std,10170.746679,NaN,803.667449,0.049632,0.0,3.425994,3.620779,0.436928,4.534196,4.142039,...,0.360444,0.037268,0.032824,0.229541,0.457221,0.350824,0.453462,0.409783,0.0,0.0
min,0.000000,NaN,1.000000,0.000000,1.0,1.000000,1.000000,0.000000,1975.000000,2003.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,8807.750000,NaN,587.000000,1.000000,1.0,3.000000,3.000000,0.000000,2004.000000,2006.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
50%,17615.500000,NaN,800.000000,1.000000,1.0,6.000000,6.000000,0.000000,2007.000000,2009.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
75%,26423.250000,NaN,1119.000000,1.000000,1.0,9.000000,10.000000,1.000000,2011.000000,2014.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.0
max,35231.000000,NaN,14660.000000,1.000000,1.0,12.000000,12.000000,1.000000,2103.000000,2017.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0

In [82]:
da_u_dumm = pd.get_dummies(data.da_university, 'da_', dummy_na = True)

In [83]:
da_u_dumm.head()

,da__albany,da__bostoncollege,da__brooklyn,da__buffalo,da__cornell,da__creighton,da__detroit,da__fordham,da__georgetown,da__georgewashington,...,da__tennessee,da__touro,da__unknown,da__vermont,da__washburn,da__washingtonandlee,da__westernmichigan,da__westernnewengland,da__yale,da__nan
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [98]:
data.Defense = list(map(lambda x: x.lower() if isinstance(x,str) else x, data.Defense))

In [108]:
data.Defense.value_counts()

legal aid society    3388
public defender      2138
legal aid bureau     1257
conflict defender     165
Name: Defense, dtype: int64

In [107]:
data.Defense.replace('conflict defender;legal aid bureau','conflict defender',inplace=True)

In [109]:
defense_dumm = pd.get_dummies(data.Defense, 'defense_', dummy_na = True)

In [110]:
defense_dumm.head()

,defense__conflict defender,defense__legal aid bureau,defense__legal aid society,defense__public defender,defense__nan
0,0,0,0,0,1
1,0,0,0,0,1
2,0,0,1,0,0
3,0,0,0,0,1
4,0,0,1,0,0

In [128]:
defense_dumm.shape[0]

35232

In [111]:
data1 = pd.concat([data, da_u_dumm])

In [112]:
data1.drop('Defense',axis=1, inplace=True)

In [123]:
defense_dumm.reset_index(drop=True, inplace=True)
data.reset_index(drop=True, inplace=True)

In [132]:
defense = pd.concat([data.File, defense_dumm],axis=1)

In [133]:
defense

,File,defense__conflict defender,defense__legal aid bureau,defense__legal aid society,defense__public defender,defense__nan
0,2009_08295.htm.txt,0,0,0,0,1
1,2009_08296.htm.txt,0,0,0,0,1
2,2009_08297.htm.txt,0,0,1,0,0
3,2009_08298.htm.txt,0,0,0,0,1
4,2009_08311.htm.txt,0,0,1,0,0
5,2009_08312.htm.txt,0,0,0,0,1
6,2009_08313.htm.txt,0,0,0,0,1
7,2009_08314.htm.txt,0,0,0,0,1
8,2009_08315.htm.txt,0,0,0,1,0
9,2009_08316.htm.txt,0,0,0,1,0
10,2009_08317.htm.txt,0,0,0,1,0
11,2009_08329.htm.txt,0,0,0,1,0
12,2009_08330.htm.txt,0,0,0,1,0
13,2009_08331.htm.txt,0,0,0,1,0
14,2009_08332.htm.txt,0,0,0,1,0
15,2009_08333.htm.txt,0,0,0,0,1
16,2009_08334.htm.txt,0,0,0,0,1
17,2009_08338.htm.txt,0,0,0,0,1
18,2009_08339.htm.txt,0,0,0,0,1
19,2009_08340.htm.txt,0,0,0,1,0
20,2009_08341.htm.txt,0,0,0,0,1
21,2009_08342.htm.txt,0,1,0,0,0
22,2009_08343.htm.txt,0,1,0,0,0
23,2009_08344.htm.txt,0,0,0,0,1
24,2009_08345.htm.txt,0,0,0,1,0
25,2009_08346.htm.txt,0,0,0,0,1
26,2009_08347.htm.txt,0,0,0,0,1
27,2009_08354.htm.txt,0,0,0,1,0
28,2009_08355.htm.txt,0,0,0,0,1
29,2009_08356.htm.txt,0,0,0,1,0
...,...,...,...,...,...,...
35202,2017_06301.htm.txt,0,0,0,0,1
35203,2017_06302.htm.txt,0,0,0,0,1
35204,2017_06303.htm.txt,0,0,0,0,1
35205,2017_06304.htm.txt,0,0,0,0,1
35206,2017_06324.htm.txt,0,0,0,0,1
35207,2017_06325.htm.txt,0,0,0,1,0
35208,2017_06326.htm.txt,0,0,0,1,0
35209,2017_06334.htm.txt,0,0,0,0,1
35210,2017_06335.htm.txt,0,0,0,0,1
35211,2017_06369.htm.txt,0,0,0,0,1
35212,2017_06370.htm.txt,0,0,0,0,1
35213,2017_06371.htm.txt,0,0,0,0,1
35214,2017_06372.htm.txt,0,0,0,0,1
35215,2017_06373.htm.txt,0,0,0,0,1
35216,2017_06374.htm.txt,0,0,0,0,1
35217,2017_06375.htm.txt,0,0,0,0,1
35218,2017_06376.htm.txt,0,0,0,0,1
35219,2017_06377.htm.txt,0,0,0,0,1
35220,2017_06378.htm.txt,0,0,0,0,1
35221,2017_06379.htm.txt,0,0,0,0,1
35222,2017_06380.htm.txt,0,0,0,0,1
35223,2017_06381.htm.txt,0,0,0,0,1
35224,2017_06382.htm.txt,0,0,0,0,1
35225,2017_06383.htm.txt,0,0,0,0,1
35226,2017_06384.htm.txt,0,0,0,0,1
35227,2017_06385.htm.txt,0,0,0,0,1
35228,2017_06386.htm.txt,0,0,0,0,1
35229,2017_06387.htm.txt,0,0,0,0,1
35230,2017_06388.htm.txt,0,0,0,0,1
35231,2017_06389.htm.txt,0,0,0,0,1

In [134]:
defense.to_csv('defense.csv')